// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQIWqXc9Cn_45tpQoAPwR3VhgrvMtldfc',
    appId: '1:472897157244:web:7c12edd536116e7c3571f9',
    messagingSenderId: '472897157244',
    projectId: 'performance-os',
    authDomain: 'performance-os.firebaseapp.com',
    storageBucket: 'performance-os.firebasestorage.app',
    measurementId: 'G-B53N3FZFW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ43dBXJUZ40YxUs3_wlK_LYZqaVL0M8o',
    appId: '1:472897157244:android:9429cf72c35e6a5a3571f9',
    messagingSenderId: '472897157244',
    projectId: 'performance-os',
    storageBucket: 'performance-os.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh1BfkDGlPGWQghvzKGA_NNy9OVSf0sN0',
    appId: '1:472897157244:ios:1cf25e6c2b8bc1413571f9',
    messagingSenderId: '472897157244',
    projectId: 'performance-os',
    storageBucket: 'performance-os.firebasestorage.app',
    iosBundleId: 'com.performanceos.app',
  );
}
